config/routes.rb
Rails.application.routes.draw do
  resources :videos, only: [:index]
  resources :playlists do
    member do
      post 'add_video'
      delete 'remove_video'
    end
  end
  root 'videos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_videos, class_name: 'PlaylistVideo', foreign_key: 'playlist_id'
  has_many :videos, through: :playlist_videos

  validates :name, presence: true
end

app/models/playlist_video.rb
class PlaylistVideo < ApplicationRecord
  belongs_to :playlist
  belongs_to :video
end

class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy, :add_video, :remove_video]

  def index
    @playlists = Playlist.all
  end

  def show
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)
    if @playlist.save
      redirect_to @playlist, notice: 'Playlist was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to @playlist, notice: 'Playlist was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @playlist.destroy
    redirect_to playlists_url, notice: 'Playlist was successfully destroyed.'
  end

  def add_video
    @video = Video.find(params[:video_id])
    @playlist.videos << @video unless @playlist.videos.include?(@video)
    redirect_to @playlist, notice: 'Video was successfully added to playlist.'
  end

  def remove_video
    @video = Video.find(params[:video_id])
    @playlist.videos.delete(@video)
    redirect_to @playlist, notice: 'Video was successfully removed from playlist.'
  end

  private

  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

  def playlist_params
    params.require(:playlist).permit(:name)
  end
end

app/models/video.rb
class Video < ApplicationRecord
  has_many :playlist_videos, class_name: 'PlaylistVideo'
  has_many :playlists, through: :playlist_videos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy, :add_video, :remove_video]

  def index
    @playlists = Playlist.all

    respond_to do |format|
      format.html
      format.json { render json: @playlists.to_json(include: :videos) }
    end
  end

  def show
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)
    if @playlist.save
      redirect_to @playlist, notice: 'Playlist was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to @playlist, notice: 'Playlist was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @playlist.destroy
    redirect_to playlists_url, notice: 'Playlist was successfully destroyed.'
  end

  def add_video
    @video = Video.find(params[:video_id])
    @playlist.videos << @video unless @playlist.videos.include?(@video)
    respond_to do |format|
      format.html { redirect_to @playlist, notice: 'Video was successfully added to playlist.' }
      format.json { head :no_content }
    end
  end

  def remove_video
    @video = Video.find(params[:video_id])
    @playlist.videos.delete(@video)
    respond_to do |format|
      format.html { redirect_to @playlist, notice: 'Video was successfully removed from playlist.' }
      format.json { head :no_content }
    end
  end

  private

  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

  def playlist_params
    params.require(:playlist).permit(:name)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    if params[:search].present?
      @videos = Video.where('title ILIKE ?', "%#{params[:search]}%").page(params[:page]).per(10)
    else
      @videos = Video.page(params[:page]).per(10)
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render plain: "Hello, World!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">VideoApp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Playlists', playlists_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/playlists/add_video.html.erb
<h1>Playlists#add_video</h1>
<p>Find me in app/views/playlists/add_video.html.erb</p>

app/views/playlists/create.html.erb
<h1>Playlists#create</h1>
<p>Find me in app/views/playlists/create.html.erb</p>

app/views/playlists/index.html.erb
<h1>Playlists</h1>

<%= link_to 'New Playlist', new_playlist_path %>

<ul>
  <% @playlists.each do |playlist| %>
    <li>
      <%= link_to playlist.name, playlist %>
      <%= link_to 'Edit', edit_playlist_path(playlist) %>
      <%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

<%= link_to 'Back to Videos', videos_path %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= form_with(model: @playlist, local: true) do |form| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
        <% @playlist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/remove_video.html.erb
<h1>Playlists#remove_video</h1>
<p>Find me in app/views/playlists/remove_video.html.erb</p>

app/views/playlists/show.html.erb
<h1><%= @playlist.name %></h1>

<h2>Videos</h2>
<ul>
  <% @playlist.videos.each do |video| %>
    <li>
      <%= video.title %>
      <%= link_to 'Remove', remove_video_playlist_path(@playlist, video_id: video.id), method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

<h2>Add Video</h2>
<%= form_with url: add_video_playlist_path(@playlist), method: :post, local: true do %>
  <div class="field">
    <%= label_tag :video_id, 'Video' %>
    <%= select_tag :video_id, options_from_collection_for_select(Video.all, :id, :title) %>
  </div>
  <div class="actions">
    <%= submit_tag 'Add Video' %>
  </div>
<% end %>

<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>

app/views/videos/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= form_with url: videos_path, method: :get, local: true do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "Search videos", class: "form-control" %>
        </div>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <% @videos.each do |video| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <img class="card-img-top video-component" src="<%= video.thumbnail_url %>" alt="<%= video.title %>">
          <div class="card-body">
            <h5 class="card-title video-title" style="height: 3em; overflow: hidden;"><%= video.title %></h5>
            <p class="card-text video-description" style="height: 5em; overflow: hidden;"><%= video.description %></p>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#videoModal" data-video-id="<%= video.video_id %>" data-description="<%= j video.description %>" data-title="<%= j video.title %>" data-id="<%= video.id %>">
              Watch Video
            </button>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= paginate @videos, theme: 'bootstrap4' %>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="videoModalLabel">Video Player</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <iframe id="videoPlayer" width="100%" height="315" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <p id="fullDescription"></p>
        <h5>Playlists</h5>
        <ul id="playlistsForVideo"></ul>
        <h5>Add to Playlist</h5>
        <form id="addVideoToPlaylistForm" method="post">
          <div class="form-group">
            <select id="playlistSelect" class="form-control">
              <% Playlist.all.each do |playlist| %>
                <option value="<%= playlist.id %>"><%= playlist.name %></option>
              <% end %>
            </select>
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary">Add to Playlist</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener('turbolinks:load', function() {
    $('#videoModal').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget);
      var videoId = button.data('video-id');
      var videoTitle = button.data('title');
      var videoDescription = button.data('description');
      var videoElementId = button.data('id');
      var modal = $(this);

      modal.find('.modal-title').text(videoTitle);
      modal.find('#videoPlayer').attr('src', 'https://www.youtube.com/embed/' + videoId);
      modal.find('#fullDescription').text(videoDescription);

      // Clear existing playlists
      $('#playlistsForVideo').empty();

      // Fetch playlists for video
      $.ajax({
        url: '/playlists',
        method: 'GET',
        success: function(playlists) {
          playlists.forEach(function(playlist) {
            if (playlist.videos.some(video => video.id === videoElementId)) {
              $('#playlistsForVideo').append('<li>' + playlist.name + ' <a href="#" data-playlist-id="' + playlist.id + '" class="remove-from-playlist">x</a></li>');
            }
          });
        }
      });

      // Update form action
      $('#addVideoToPlaylistForm').off('submit').on('submit', function(event) {
        event.preventDefault();
        var playlistId = $('#playlistSelect').val();
        $.ajax({
          url: '/playlists/' + playlistId + '/add_video',
          method: 'POST',
          data: { video_id: videoElementId },
          success: function() {
            $('#videoModal').modal('hide');
          }
        });
      });

      $(document).off('click', '.remove-from-playlist').on('click', '.remove-from-playlist', function(event) {
        event.preventDefault();
        var playlistId = $(this).data('playlist-id');
        $.ajax({
          url: '/playlists/' + playlistId + '/remove_video',
          method: 'DELETE',
          data: { video_id: videoElementId },
          success: function() {
            $('#videoModal').modal('hide');
          }
        });
      });
    });

    $('#videoModal').on('hide.bs.modal', function () {
      $('#videoPlayer').attr('src', '');
    });
  });
</script>

app/views/videos/search.html.erb
<h1>Videos#search</h1>
<p>Find me in app/views/videos/search.html.erb</p>